language: python
python:
- "3.5"
- "3.6"

install:
- pip install pytype
- pip install pycodestyle
- pip install termcolor

script:
- pytype --config=pytype.cfg --python-version=$TRAVIS_PYTHON_VERSION
- pytest
- pycodestyle .
