language: python

# As demonstrated in https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

script:
- echo "Travis Python version: $TRAVIS_PYTHON_VERSION"
- pytype --config=pytype.cfg --python-version=$TRAVIS_PYTHON_VERSION
- python -m pytest
- pycodestyle .
