# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: mypy
          command: |
            . venv/bin/activate
            mypy \
                src/echo/bc_helpers.py \
                src/echo/builtin_bytearray.py \
                src/echo/builtin_enumerate.py \
                src/echo/builtin_int.py \
                src/echo/builtin_iter.py \
                src/echo/builtin_object.py \
                src/echo/builtin_predicates.py \
                src/echo/builtin_str.py \
                src/echo/builtin_sys_module.py \
                src/echo/builtin_type.py \
                src/echo/bytecode_trace.py \
                src/echo/code_attributes.py \
                src/echo/common.py \
                src/echo/common_test.py \
                src/echo/dso_objects.py \
                src/echo/ebuiltins.py \
                src/echo/ecell.py \
                src/echo/elog.py \
                src/echo/emap.py \
                src/echo/eproperty.py \
                src/echo/emodule.py \
                src/echo/eobjects.py \
                src/echo/epy_object.py \
                src/echo/eclassmethod.py \
                src/echo/estaticmethod.py \
                src/echo/etraceback.py \
                src/echo/guest_objects_test.py \
                src/echo/__init__.py \
                src/echo/interp_context.py \
                src/echo/interp_result.py \
                src/echo/interpreter_state.py \
                src/echo/interp_routines.py \
                src/echo/iteration_helpers.py \
                src/echo/oo_builtins.py \
                src/echo/return_kind.py \
                src/echo/tracediff.py \
                src/echo/trace_util.py \
                src/echo/value.py

      - run:
          name: pytest
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: pytype
          command: |
            . venv/bin/activate
            pytype --config=pytype.cfg --python-version=3.7

      - run:
          name: pycodestyle
          command: |
            . venv/bin/activate
            pycodestyle src/ tests/
