# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: mypy
          command: |
            . venv/bin/activate
            mypy \
                src/echo/bc_helpers.py \
                src/echo/builtin_int.py \
                src/echo/builtin_type.py \
                src/echo/builtin_str.py \
                src/echo/builtin_enumerate.py \
                src/echo/builtin_predicates.py \
                src/echo/epy_object.py \
                src/echo/dso_objects.py

      - run:
          name: pytest
          command: |
            . venv/bin/activate
            pytest

      - run:
          name: pytype
          command: |
            . venv/bin/activate
            pytype --config=pytype.cfg --python-version=3.7

      - run:
          name: pycodestyle
          command: |
            . venv/bin/activate
            pycodestyle src/ tests/
